"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-clew' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
# NOTE: scitex_clew self-imports (scitex_clew, scitex_clew._claim,
# scitex_clew._cli, scitex_clew._dag) are deliberately omitted — the
# scitex-dev auditor disagrees with itself on whether self-imports
# belong in the cross-package gate ("missing" verdict in some envs,
# "stale" verdict once added). This is an upstream auditor bug
# (`_check_umbrella_dep_and_integration._own_import_name` derives the
# own-name from the repo directory basename — see scitex-ml PR #8
# for the full diagnosis). Keep the gate to genuine cross-package
# imports only; the CI auditor sees these as "stale" if added.
CROSS_PACKAGE_IMPORTS = [
    "scitex_dev._cli._completion",
    "scitex_dev.cli",
    "scitex_dev.decorators",
    "scitex_io",
    "scitex_logging",
    "scitex_session",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-clew's declared cross-package dependency must succeed."""
    # Arrange
    # Act
    module = pytest.importorskip(module_name)
    # Assert
    assert getattr(module, "__name__", None) == module_name
