#!/usr/bin/env python3
# Timestamp: "2026-06-27 (ywatanabe)"
"""Claims JSON export utility."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Optional, Union

from ._db_ops import list_claims


def export_claims_json(
    path: Optional[Union[str, Path]] = None,
    *,
    file_path_filter: Optional[str] = None,
    read_only: bool = True,
) -> Path:
    """Export every registered claim to a canonical JSON artifact.

    The exported file is the single human-readable + machine-consumable
    view of the claims table in ``db.sqlite``. The DB remains the
    source of truth; this JSON is a regenerable artifact.

    Path resolution (mirrors :func:`scitex_clew._db._core._default_db_path`)::

        1. Explicit ``path`` argument.
        2. ``$SCITEX_CLEW_CLAIMS_JSON`` env var (escape hatch).
        3. ``<project_root>/.scitex/clew/runtime/claims.json``
           (project root = nearest ancestor dir with ``.git`` or
           ``pyproject.toml``; falls back to cwd if none found).

    Parameters
    ----------
    path : str | Path, optional
        Override the resolved path. Useful for tests / one-off dumps.
    file_path_filter : str, optional
        When set, only claims registered against this manuscript file
        path are exported. Default: every claim in the DB.
    read_only : bool, optional
        After writing, ``chmod 0o444`` the file so accidental edits
        fail loudly at the OS layer. Default True (the file IS
        derived). Set False for tests that need to mutate the file.

    Returns
    -------
    Path
        The path the artifact was written to (absolute).

    Examples
    --------
    >>> import scitex_clew as clew
    >>> clew.add_claim("paper.tex", "value", 42, "0.94", source_file="r.csv")
    >>> # claims.json now auto-exported under ./.scitex/clew/runtime/
    >>> clew.export_claims_json()  # idempotent — re-emit on demand
    PosixPath('.../.scitex/clew/runtime/claims.json')
    """
    from .._db import _core as _db_core

    if path is None:
        env_path = os.environ.get("SCITEX_CLEW_CLAIMS_JSON")
        if env_path:
            path = Path(env_path)
        else:
            path = _db_core._default_claims_json_path(_db_core._find_project_root())
    path = Path(path).resolve()
    path.parent.mkdir(parents=True, exist_ok=True)

    claims = list_claims(file_path=file_path_filter, limit=10_000)
    payload = {
        "_note": (
            "AUTO-GENERATED by scitex_clew.export_claims_json() from "
            "db.sqlite. Do NOT edit by hand — re-emit by calling "
            "scitex_clew.export_claims_json() (default-on after every "
            "clew.add_claim()) or by re-running your pipeline."
        ),
        "claims_count": len(claims),
        "claims": [c.to_dict() for c in claims],
    }

    # Clear any pre-existing read-only bit before rewriting.
    if path.exists():
        try:
            path.chmod(0o644)
        except OSError:
            pass

    path.write_text(json.dumps(payload, indent=2, default=str))

    if read_only:
        try:
            path.chmod(0o444)
        except OSError:
            # Best-effort — on filesystems that don't support unix
            # perms (e.g. some Windows mounts) this is a no-op.
            pass

    return path


# EOF
