"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package(
        "scitex-clew",
        skip_rules=(
            # MCP tool coverage gap — 17/31 Python APIs are not yet exposed as
            # MCP tools. Real architectural debt; per-API decision needed for
            # each one. Tracked under /overhaul-scitex.
            "§6",
        ),
    )
