"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest


def test_audit_all_clean():
    # Arrange
    # Act
    # Assert
    # Arrange
    # Act
    # Assert
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    # PA-307 §3 test-quality (TQ001/TQ007 backlog) has been remediated
    # structurally — multi-assertion tests were split and the lone
    # no-assertion test now asserts behaviour. §6 audit-mcp-tools (17 of
    # 31 Python APIs missing a matching MCP tool wrapper) is an
    # architectural follow-up tracked in a separate issue; it is NOT
    # masked here per the operator hard rule against `skip_rules` masking.
    audit_all_for_package('scitex-clew', skip_rules=())
